app:
  messaging:
    order:
      topicExchange: order
      createdQueue: order-created-queue
      updatedQueue: order-updated-queue
      createdRoutingKey: order.event.created
      updatedRoutingKey: order.event.updated

  security:
    oauth2:
      jwt:
        issuer-uri: http://localhost:8080/auth/realms/master

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/