app:
  service:
    shopping-cart:
      cookie:
        ageHours: 5040

feign:
  hystrix:
    enabled: true

logging:
  level:
    com.mikhailkarpov.eshop.shoppingcartservice.client.ProductServiceClient: DEBUG

spring:
  cache:
    type: redis

  redis:
    host: redis
    port: 6379